### PR TITLE
Handful of changes to VirusTotal module

### PR DESCRIPTION
**Pull request by kx499**
fixed spacing in some spots (2 vs 4) 
Addressed error handling for using it via the public api. 500/403's woudl cause .json() to barf. 
Added paring for subdomains
Added context comment to identify what value was queried to return the attribute. This is useful with the nested/recursive look-ups to tie back information to value it is related to.

### CODE REVIEW

**Comment by kx499** [comment]
Apparently it added the iprep module to this pr. I committedd it to my fork after pr. I guess it just sucks in all changes, even ones after the pr. not sure why - that module should be good to go as well.

**Comment by Rafiot** [comment]
No problem, merging now :)

FYI, anything you add in the same branch the PR is based on will be added. If you want to keep some commits out of a PR, you need to do this commit in an other branch.

**Comment by Rafiot** [comment]
Here it is: https://github.com/MISP/misp-modules/commit/44867b2adc00777ecb44fb481ab58d88623d64f8

Can you give a try, pease?

**Comment by kx499** [comment]
Thanks. Looks good and works. Thanks for the tip on raise_for_status.

**Comment by Rafiot** [comment]
:+1: 

and you're welcome

**Pull request merged**
