### PR TITLE
Simple import module to import MISP JSON format

### PR DESCRIPTION
**Pull request by RichieB2B**
Adding attachments ("data" content) doesn't work, but I blame MISP.

### CODE REVIEW

**Comment by adulau** [comment]
Thank you for the contribution. Just wondering, what's the objective compared to the default MISP JSON import? Your module is more populating a new event (new UUID) and adding attributes from another MISP event. The MISP JSON import (in the core) is more to import completely an existing event and to avoid duplicate. Is this the intended use case?

**Comment by RichieB2B** [comment]
The intended use case is to merge attributes from existing events together in a new event. Effectively creating copies of the attributes.

**Comment by adulau** [comment]
Perfect. Could you just update the description to specify this use case? Then I'll merge it. Thank you very much,

**Comment by adulau** [comment]
@RichieB2B When you have time, could you just update the description? Thanks a lot.

**Comment by RichieB2B** [comment]
Something like 3a4c540a81bbb36c45b50e98cb71ce14a441fe5b ?

**Comment by adulau** [comment]
Looks very good. Thank you.

**Pull request merged**
