### PR TITLE
Upgrade censys_enrich module to new api version

### PR DESCRIPTION
**Pull request by slv008**

### CODE REVIEW

**Comment by adulau** [comment]
Thank you very much for the pull-request. Could you update the test case? It's currently failing in the default workflow as seen above.

**Comment by slv008** [comment]
Hello @adulau - it should be fixed now along with some extra additions. Thank you

**Comment by adulau** [comment]
Thanks a lot. A last one is to check the config value is set to `None` too for the test. Then I'll merge it.

**Comment by adulau** [comment]
Thanks a lot!

**Pull request merged**
