### PR TITLE
Module to push malware samples to a MWDB instance

### PR DESCRIPTION
**Pull request by cudeso**
- Upload of attachment or malware sample to MWDB
- Tags of events and/or attributes are added to MWDB.
- Comment of the MISP attribute is added to MWDB.
- A link back to the MISP event is added to MWDB via the MWDB attribute.
- A link to the MWDB attribute is added as an enriched attribute to the MISP event.

### CODE REVIEW

**Comment by cudeso** [comment]
Python build jobs are failing on missing "**mwdblib**". I don't think that this should be included in the REQUIREMENTS file ... but happy to update the PR if this could make the job complete successfully.

**Comment by adulau** [comment]
Could you add it in the requirements ? Thanks a lot.

**Comment by cudeso** [comment]
@adulau REQUIREMENTS file updated; all checks have passed

**Comment by adulau** [comment]
Great stuff! Thank you very much. I’m sure NASK/CERT-PL would be happy too.

**Pull request merged**
