### PR TITLE
initial hashstore commit for misp-module

### PR DESCRIPTION
**Pull request by truckydev**
## What is this:
A simple way to check if a value is in your misp instance.

To use this, you need this : 
https://github.com/MISP/MISP/pull/3157
https://github.com/MISP/MISP/pull/3158

## how to use : 
1 - init your hashtore with hashstore_init.py
2 - lunch the hashstore_sub.py to be uptodate with misp
3 - activate hashstore module in misp administration
4 - lunch the test with hashstore_test.py

### CODE REVIEW

**Comment by iglocska** [comment]
I see several issues here such as going to mysql directly from an external tool, along with using an expansion module for correlations. Could you explain what issue you are trying to solve here and we could think about a better way of doing this.

**Comment by adulau** [comment]
Thank you for the PR. Looking at the module, I saw that you directly access the SQL interface. misp-modules is intended to work without direct interaction with MISP beside the module HTTP ReST API (many users used in a DMZ or alike to limit security risks).

The idea is cool (e.g. NSLR database or even MISP where you don't have access to) but I would separate it in the following way (if you just want quick lookup against a Redis hash store):

- Have a separate server (with a ReST API) and using Redis for the hash store which is getting the update from the ZMQ feed of MISP or via CakePHP command line.
- Then the module will query the API of your server (like we do for the CVE expansion).

So I see the opportunity to build a separate project in MISP which can be a generic hash store.

**Comment by truckydev** [comment]
Thank you very much for your return.

The part using the SQL query is just used to initialize the database with the existing data.
maybe initiate this one on misp server, next export and import in another redis used by misp-modules.
I have take the easy way here where misp and misp-module are installed on the same machine.

If you check hashtore_sub.py, the db receives updates from the pubsub.
maybe adapte this script to update the an other redis database use my misp-midule.

The actual usage is something like this : 
```bash
curl -X POST http://misp.local/modules/queryEnrichment/ 
-H "Accept: application/json" 
-H "content-type: application/json" 
-H "Authorization: XXXXXXX"  
-d '{"module": "hashstore",  
  "hashs": [
      "0002969c86f26bf044714999910ca15c1397365ff4db9b752078a425b5dac8b5",
      "003681a69aecd31b1d8ffd870fc0b91c2d68c46694d98d8c13bdd7ab0620d46e"
    ], "quick_search" : "True"}' |jq
```
Or with python you can check hashstore_test.py 
The benefit of this solution is that it uses misp authentication :) and don't expose misp-modules.

**Comment by adulau** [comment]
Thank you for the feedback. It's great. As discussed, I'll open a new repository for the hashstore project. I'll keep this one as reference until we finalise a module.

**Comment by adulau** [comment]
FYI, we new export format has been added in restSearch to export hashed values of the attributes, you can now query like this with the cache output format (MD5 of all the attributes):

~~~~
{
    "returnFormat": "cache",
    "limit": "100"
}
~~~~

This can be used as a basis for a new hashstore export.

**Comment by adulau** [comment]
@truckydev did you have time to look at the cache restSearch (all the hashes from PHP are supported as output)? I'll close the issue.  Let us know if this is fine. Thanks a lot.

**Pull request closed without merging**
