### PR TITLE
Added (Multipage) PDF support to OCR Module, minor refactor

### PR DESCRIPTION
**Pull request by SteveClement**
Quick and dirty PDF implementation using Wand: http://docs.wand-py.org/en/0.4.4/
Refactored the python module loading, in case the module is not installed it will yield an error for MISP to display.

It will stitch together one big PNG out of all the pages included in a PDF.

Gotchas: 

- Huge PDFs might fail on timeouts, solution -> async foo
- Weirdly formatted PDFs might fail, solution -> Print it and recreate the PDF, resubmit

### CODE REVIEW

**Comment by SteveClement** [comment]
Currently broken, do not pull

**Comment by adulau** [comment]
~~~~
======================================================================
ERROR: Failure: SyntaxError (invalid syntax (ocr.py, line 59))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/imp.py", line 217, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/travis/build/MISP/misp-modules/misp_modules/modules/__init__.py", line 2, in <module>
    from .import_mod import *
  File "/home/travis/build/MISP/misp-modules/misp_modules/modules/import_mod/ocr.py", line 59
    log.debug(f"PDF with {pages} page(s) detected")
~~~~

It seems the syntax doesn't work with older version of Python 3.

**Comment by Rafiot** [comment]
No, it doesn't: https://cito.github.io/blog/f-strings/

What is the oldest version of Python3 we want to support?

**Comment by adulau** [comment]
It's a 3.6 feature ;-)

3.4 which is supported until 2019 and 3.5 until mid-2020 
33826009-275286e4-de6c-11e7-8f70-781433006423

**Comment by SteveClement** [comment]
Reverted to a more friendly 3.x version :)

Thanks to @adulau for adding the magical version history table to the relevant place(s) :)

**Comment by adulau** [comment]
Thank you very much for the contribution and improving the "original hack" of the OCR module to something usable ;-)

**Pull request merged**
