### PR TITLE
Lite export of an event

### PR DESCRIPTION
**Pull request by truckydev**
This module export an event with minimal information.

The field don't work. for more configuration bye admin view :(

### CODE REVIEW

**Comment by adulau** [comment]
Nice idea! Thank you.

**Comment by truckydev** [comment]
Avec plaisir Alexandre.

J'avais fais la partie lite au dernier hackathon dans misp (pour pouvoir faire /events/view/2-min.json) mais Raphaël me disait qu'un module serait plus approprié ^^

Au besoin, je peux faire le pull/request

**Comment by adulau** [comment]
I like the idea. We could even expand the module to have a kind of "privacy-aware" module which can only export the events following set of criteria depending of the categories and attributes used.

**Comment by truckydev** [comment]
Yes, but in this one, we take just event.info, attribut.catégorie, attribut.type, attribut.value.

I can check if event.distribution is "1" too for exemple or if tag is tlp:width ...

I would like to add this in the configuration but it does not work. The module does not retrieve the request["config"] value. that's why I have commented : 
https://github.com/MISP/misp-modules/pull/106/files#diff-da818866538c5f5f3b42c979215a317dR12

**Comment by truckydev** [comment]
I exclude 'Internal reference' too but I think this should be configurable.

**Pull request merged**
