### PR TITLE
Add web documentation via mkdocs

### PR DESCRIPTION
**Pull request by 8ear**
I copied the configuration from MISP/MISP project about MKDOCS. Therefore the misp-modules get a real documentation page for his project and not only two markdown pages.
I reused the existing documentation and mkdocs should be seen as an alternative one.

If you want to change any, please do it. :-)

Kind regards

### CODE REVIEW

**Comment by 8ear** [comment]
Hi @adulau ,
To make travis CI happy please add a deploy token to the github repository and add this deploy token as `$GITHUB_TOKEN`  in the travis CI settings page for this repository, as a secure variable

**Comment by adulau** [comment]
Thank you very much for the contribution. I enabled to the site for misp-modules. Maybe there is something I don't get but all the other Markdown for the modules are not generated by GitHub.  We need to look into it.

**Comment by 8ear** [comment]
Hi @adulau ,
The problem is you have not created a deploy key and added it to travis CI misp-modules project settings. :-)

you see it here: https://travis-ci.org/MISP/misp-modules/jobs/566472742#L1000

If you comment it out not token is there!
https://github.com/MISP/misp-modules/commit/b8ed5eca9e224c0163a1da382fffea29b968e64c#diff-354f30a63fb0907d4ad57269548329e3

**Comment by 8ear** [comment]
Here is the link from Travis docs: https://docs.travis-ci.com/user/deployment/pages/

**Comment by adulau** [comment]
I know but I don't plan to make the deployment via Travis ;-) We do it indirectly.

Have you an idea why the other markdown pages are not generated?

**Comment by 8ear** [comment]
Do you do it with my Makefile?
I had a command with a dockerfile to generate site directory an all other and then it enough to do  `mkdocs gh-deploy`. It is the best to modify the makefile for that.

**Comment by 8ear** [comment]
In my local example with the container he generated all in site directory and this you can copy to gh-pages branch

**Pull request merged**
