### PR TITLE
Cytomic Orion MISP Module

### PR DESCRIPTION
**Pull request by cudeso**
An expansion module to enrich attributes in MISP and share indicators
of compromise with Cytomic Orion

### CODE REVIEW

**Comment by cudeso** [comment]
Failures not related to the new module? (FAIL: test_btc_steroids (tests.test_expansions.TestExpansions) )

**Comment by adulau** [comment]
All good, no worries. Could you add the documentation JSON file for the module? To have a nice entry in the documentation. Thanks a lot!

**Comment by cudeso** [comment]
Documentation added.

**Comment by adulau** [comment]
Top! Thank you very much.

**Pull request merged**
