### PR TITLE
Change to pandas version requirement to address pip install failure

### PR DESCRIPTION
**Pull request by adammchugh**
Updated pandas version to 1.1.5 to allow pip install as defined at https://github.com/MISP/misp-modules to complete successfully.

### CODE REVIEW

**Comment by adulau** [comment]
Thank you!

**Comment by JakubOnderka** [comment]
Hello @adammchugh, where did you found `censys==1.26.3`? Because last available version on PyPI is 1.1.1: https://pypi.org/project/censys/

**Comment by adammchugh** [comment]
Interesting. I initially installed censys manually prior to running the
install with REQUIREMENTS and the reported version came out as 1.26.3.

My ammendment to the REQUIREMENTS file only stipulated the version to keep
with the formatting of the rest of the file.

**Comment by eCrimeLabs** [comment]
I'm experiencing the same issues attempting to pull the Censys through pip as @JakubOnderka  mentioned
```
Collecting blockchain==1.4.4
  Using cached blockchain-1.4.4-py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement censys==1.26.3
ERROR: No matching distribution found for censys==1.26.3
```

**Comment by adammchugh** [comment]
Ok, looks like I goofed the version somehow. I can't redo the PR from where
I am now, but i'd suggest the version is changed to the latest as discussed
earlier.

**Pull request merged**
