### PR TITLE
Enable / Disable plugins

### PR DESCRIPTION
**Pull request by stricaud**
This set of patches allow to leave your plugins as available, but disabling them by just removing a symlink. 
I moved all the plugins into the subdirectory modules/available and linked from modules/enabled all of them to keep the actual default standard loading.
This should not change anything, but simply allow anyone to remove/add symlinks to modules they want loaded.

### CODE REVIEW

**Comment by adulau** [comment]
This is a cool idea. Could you fix the test case to make Travis happy? :cocktail:

**Comment by stricaud** [comment]
sure, will work on this.

**Comment by 8ear** [comment]
How to enable / disable modules? Is there a tools like Apache2 a2enmod/a2dismod?

**Comment by adulau** [comment]
@stricaud it seems to be fixed in  #311 feel free to make a new pr if needed. Thanks a lot.

**Pull request closed without merging**
