### PR TITLE
Added expansion for Wikidata. 

### PR DESCRIPTION
**Pull request by rgraf**
Analyst can query Wikidata by label to get additional information for particular term.

### CODE REVIEW

**Comment by rgraf** [comment]
I believe that expansion would be useful for analyst if he needs more information about particular vendor, software or something else.

**Comment by adulau** [comment]
Thank you very much for the contribution. It's merged. I just added the __init__.py and the requirements.

**Comment by adulau** [comment]
I did some test with your module but I'm wondering something about the input attribute which is label in your module: 'input': ['label'] which is not an existing attribute. Do you have a customized MISP version? text would be a correct input field. Cheers

**Comment by rgraf** [comment]
Thank you for fixes and testing. I've just started with the MISP. For my testing I've used body.json file that contains e.g. {"module":"wiki","label":"Microsoft"}. I do not yet have customized MISP version. I didn't noticed a list of existing attributes. Where could I find it? Of course, "text" should be used instead of "label". How could I fix that in a correct way?

**Comment by rgraf** [comment]
Thank you for fixes and testing. I've just started with the MISP. For my testing I've used body.json file that contains e.g. {"module":"wiki","label":"Microsoft"}. I do not yet have customized MISP version. I didn't noticed a list of existing attributes. Where could I find it? Of course, "text" should be used instead of "label". How could I fix that in a correct way?

**Comment by iglocska** [comment]
You can find a list of all the valid attribute categories and types if you go to global actions -> user guide -> Categories and types

Alternatively, you can check them out over here: 

https://www.circl.lu/doc/misp/categories-and-types/index.html

**Pull request merged**
