### PR TITLE
Update test_expansions.py

### PR DESCRIPTION
**Pull request by StefanKelm**
Tiniest of typos

### CODE REVIEW

**Comment by StefanKelm** [comment]
Anyone have an idea why Travis complains? I only changed a single character...

**Comment by StefanKelm** [comment]
Bump. ;)

**Comment by Rafiot** [comment]
Because the test case tests that typo ;)

**Comment by Rafiot** [comment]
Well, no, I'm an idiot: the typo is in a 3rd party service. The test is correct.

**Comment by StefanKelm** [comment]
Anything I can do about it? I don't really understand the problem here...

**Comment by Rafiot** [comment]
If you want to get in touch with btcblack.it -> 
https://github.com/MISP/misp-modules/blob/master/misp_modules/modules/expansion/btc_scam_check.py

Sure :)

**Comment by StefanKelm** [comment]
Well, what's interesting is, though, is that I didn't even touch btc_scam_check.py

**Comment by Rafiot** [comment]
yes, I know, it is because the answer from their API contains the typo, we just pass it straight to the user on our side.

**Pull request merged**
