### PR TITLE
Documentation Update for EQL Modules

### PR DESCRIPTION
**Pull request by blaverick62**
Updated readme, index, and description json to include new EQL modules.

### CODE REVIEW

**Comment by blaverick62** [comment]
I noticed that someone added documentation for the EQL module in json, that can be kept instead of my changes.

**Comment by chrisr3d** [comment]
No worries I can try to fix the conflict and merge it as well

**Comment by blaverick62** [comment]
Awesome, thanks for the help.

**Comment by chrisr3d** [comment]
I just fixed the conflict, merged your description and updated the documentation.
Thank you for your contribution

**Pull request merged**
