### PR TITLE
Add Recorded Future module documentation

### PR DESCRIPTION
**Pull request by hildenjohannes**

### CODE REVIEW

**Comment by adulau** [comment]
Thank you very much. Should I do a tweet from MISP Project about this module?

**Comment by hildenjohannes** [comment]
That does sound very cool! Let me get back to you once I've been in touch with marketing.

**Comment by hildenjohannes** [comment]
Marketing approves! Would it be possible to include a retweet to this tweet made by Recorded Future? https://twitter.com/RecordedFuture/status/1288119995717672960

**Comment by adulau** [comment]
I did the following https://twitter.com/MISPProject/status/1288454259814604801 - Something else which can be done is a blog post on the misp-project website. It should mainly focusing on how your module is designed and so on (not a marketing blog per se ;-).

**Comment by hildenjohannes** [comment]
Great, thank you very much! That also sounds interesting!

**Comment by hildenjohannes** [comment]
How would we go about that blog post? Do I send you a draft?

**Comment by adulau** [comment]
You can do a pull-request on misp-website with a new post:

https://github.com/MISP/misp-website/tree/master/_posts

and we will review/update it and then publish it if all is fine.

**Comment by hildenjohannes** [comment]
Great, I will put something together and do that. Thank you again!

**Comment by adulau** [comment]
Thank you too!

**Pull request merged**
