### PR TITLE
add: Modules to query/import/submit data from/to Lastline

### PR DESCRIPTION
**Pull request by ostefano**
Let me know if there is anything else I should for this PR to be merged.

### CODE REVIEW

**Comment by adulau** [comment]
Looks very good. Thank you for the contribution!

**Comment by ostefano** [comment]
@adulau Thx! I just noticed there is a file that didn't get updated: https://github.com/MISP/misp-modules/blob/master/docs/index.md Seems like that also other modules (like assembleline) are missing in this specific file. Is that expected?

**Comment by adulau** [comment]
The documentation has been regenerated. Thank you for the contribution.

**Comment by chrisr3d** [comment]
@ostefano The file you mentioned is the one that was used for documentation before.
It is no longer used, you documented everything well no worries, thank you

**Comment by ostefano** [comment]
@chrisr3d sounds good! Just to let you know the old documentation is still linked in the project's description (see screenshot)
Screenshot 2019-12-03 at 14 08 33

**Pull request merged**
