### PR TITLE
Use SpooledTemp, not NamedTemp file

### PR DESCRIPTION
**Pull request by FloatingGhost**
Loop zoop :dancer:  no more disk touchy

PyMISP also PR'd to use the right function ;)

### CODE REVIEW

**Comment by Rafiot** [comment]
wohoo :)

**Comment by Rafiot** [comment]
Hmmm, travis fails

**Comment by FloatingGhost** [comment]
yeah, it's something git related

**Comment by FloatingGhost** [comment]
o no

**Comment by FloatingGhost** [comment]
that was the other one. it updated

**Comment by FloatingGhost** [comment]
ok, it should work now. I think.

**Comment by Rafiot** [comment]
Nope :p 
https://travis-ci.org/MISP/misp-modules/jobs/177646621

**Comment by FloatingGhost** [comment]
Seriously travis?

**Comment by FloatingGhost** [comment]
DING DE LA DING

**Comment by Rafiot** [comment]
you did it! :)

**Pull request merged**
