### PR TITLE
[EUPI] Change module for a simple hover status

### PR DESCRIPTION
**Pull request by eu-pi**
This PR fixes the EUPI module so that the returned result is actually usable.

Here is it in action after this PR:

On hover, the EU Phishing Initiative project is requested via the provided API credentials, and the returned value (phishing, not phishing, unknown url to EUPI) is displayed in the tooltip.

### CODE REVIEW

**Comment by Rafiot** [comment]
We should probably create two modules, one showing the type as hover, and an other one to expand the attributes. 
What do you think?

**Comment by adulau** [comment]
I think the best is to have it as an option in the module. So it will be up to the MISP site administrator to decide what kind of output they want for the module.

**Comment by iglocska** [comment]
Maybe we need two response objects for enrichment? One for hover one for
expansion

**Comment by Rafiot** [comment]
Yeah, that would make sense, that would also avoid polluting the hover: for example, when PDNS has lots of entries, we could strip it.

**Comment by eu-pi** [comment]
Trying to take into account all your comments here.

What do you think about the following?
 - **hover**: just return the EUPI phishing status (phishing, not phishing, unknown url to EUPI) as it is the case in my first message;
 - **expansion**: do as before, offering to add what is returned by EUPI to be added as attributes.

If that's ok with everyone, I can edit my commit to do so. Since https://github.com/MISP/MISP/issues/1091 the `event_id` is set in the JSON body in the case of an expansion, so I can detect if the module should act as _hover_ or as _expansion_ based on that.

**Comment by adulau** [comment]
@eu-pi It's a nice trick (until we come with an improved approach in the modules interaction) ;-) Feel free to update your commit. Thanks a lot for your contribution.

**Comment by eu-pi** [comment]
> Feel free to update your commit. Thanks a lot for your contribution.

Done. Tell me what you think! :-)

**Comment by adulau** [comment]
The hover part is looking good. I merged it. Not sure if the expansion works as expected. Thank you very much.

**Comment by eu-pi** [comment]
Cool, thank you!

**Pull request merged**
