### PR TITLE
Added email meta-data import module

### PR DESCRIPTION
**Pull request by seamustuohy**
This email meta-data import module collects basic meta-data from an e-mail and populates an event with it. It populates the email subject, source addresses, destination addresses, subject, and any attachment file names. This commit also contains unit-tests for this module as well as updates to the readme.

**Readme updates** are additions aimed to make it easier for outsiders to build modules.They are based upon my experience building a module in my free time.

In the module there are a few **commented out sections**. This is because there are a few values that I think are useful for examining phising attacks that are currently missing. These are merely mentioned here (and stubbed out in the code) to support any future conversations. I don't currently use MISP in my work, so I don't want to push for any additional values unless they are desired by others. 

_email-dst-display-name_

The "real name" component of a destination address. (e.g. [_email-dst-display-name_] username@domain )

This can be useful for identifying the compromised source that spear-phishing emails were harvested from. By comparing to the historic destinations used by those who have e-mailed the individuals previously one can match the subset of historic accounts that have sent them mail using the specific combination of destination addresses  shown in the e-mail. This works for when some of the recipients of the email have changed the name that they use in their e-mails, or when the sender is a person who has added their e-mail address by hand into their devices.

_email-src-display-name_

The "real name" component of a source address. (e.g. '[_display-name_] code@seamustuohy.com')

Useful for helping to identify the sophistication of the phishing attack.

_email-received-path_

The received path from an e-mail to get an idea of the path it took. Even better would be this broken out, but the received header is a beast, and nearly impossible to build a working regex for.

**To Test**  run the unit-test suite from the main misp directory with python3. It will show the outputs for an email with and without an attachment.

### CODE REVIEW

**Comment by Rafiot** [comment]
Cool! I'll give a try.

**Comment by seamustuohy** [comment]
I just noticed that comments that include quotes are not showing up in the web interface. (I assume that they are accidentally being injected into the code.) Should I fix this by escaping in the module for now, or just submit a bug in MISP?

**Comment by Rafiot** [comment]
@adulau @iglocska: what do you think of `email-dst-display-name` and `email-src-display-name`? 

`email-received-path` is clearly something interesting, but I think it will be much more difficult to represent in a meaningful way.

Here is the short TODO list I'd love to have in this module.
* extract all possible URLs from the body of the mail 
* unpack the attachments (especially the zips)
* origin IP of the mail

**Comment by iglocska** [comment]
For the quotation issue, I will check what's going on there tomorrow or the day after, am currently traveling. 

For the additional attribute types - good idea, let's collect them all for a future release when we'll introduce them all in one shot: 

https://github.com/MISP/MISP/issues/1108

**Comment by seamustuohy** [comment]
@Rafiot How does one pass back attachments? When I tried I just ended up with giant text blocks sent back as a value. 

Also, what values would people prefer for the urls and the possible origin IPs?

**Comment by Rafiot** [comment]
@iglocska is it possible to pass attachments via the misp-modules? I'm not sure it is implemented in MISP core.

And regarding the values to extract, let's start with email-src, email-dst, email-subject (email-attachment if it is possible) and URLs. That's a good start and we can always improve later if needed.

**Comment by iglocska** [comment]
It's possible but somewhat tricky if I remember correctly and not documented, but we had the need for it before and I implemented a way to pass them back. Will check it out tomorrow!

**Comment by seamustuohy** [comment]
OK, with the latest addition of the [new attributes](https://github.com/MISP/MISP/wiki/NewAttributes) I'll add in functionality for those attributes It looks like there is no guidance on passing attachments to be found so I will re-ping once those are added and I've fixed any merge issues.

**Comment by Rafiot** [comment]
Passing an attachment is implemented (but not documented nor really tested...): https://github.com/MISP/PyMISP/blob/master/pymisp/mispevent.py#L185

The way to do it is to add a data parameter to an attribute (pseudo code):
``` python
me = MISPEvent()
me.info = 'My event'
me.add_attribute('malware-sample' OR 'attachment', 'filename.txt' OR 'value', data=<BytesIO>)
```
**NOTE**: 
1. for a malware sample, the value has to me the filename
2. The difference between malware-sample and attachment is that the malware sample will be zipped and password protected ('infected')

**Comment by seamustuohy** [comment]
Your a king @Rafiot! 

As an FYI, it will likely be after the holidays before I will re-submit the final request.  I finished the other attributes last night, and should be able to get this added this evening. But, I want to write and edit some basic documentation on passing an attachment in the README while I have it in my head.

**Comment by seamustuohy** [comment]
E-mail module is ready for review and integration.

New options that have been added:
- **unzip_attachments** : Unzip all zip files
- **guess_zip_attachment_passwords** : This attempts to guess the password to password protected zip files using all the strings found in the email body and subject. It checks against a [tiny basic password list](https://github.com/seamustuohy/misp-modules/blob/1a7973bc0623f2b5a01d9185baaf7e7616301b2a/misp_modules/modules/import_mod/email_import.py#L261-L269), [every individual word](https://github.com/seamustuohy/misp-modules/blob/1a7973bc0623f2b5a01d9185baaf7e7616301b2a/misp_modules/modules/import_mod/email_import.py#L310-L315), and any text that are [marked off by special characters](https://github.com/seamustuohy/misp-modules/blob/1a7973bc0623f2b5a01d9185baaf7e7616301b2a/misp_modules/modules/import_mod/email_import.py#L303) (e.g. what the parens are doing to this example.) 
- **extract_urls** : This attempts to extract all URL's from text/html parts of the email

I have also created unit-tests for the module so that each component of the functionality can be tested. It currently has [one failing test because of a newline that gets added to the reply-to field.](https://github.com/seamustuohy/misp-modules/blob/1a7973bc0623f2b5a01d9185baaf7e7616301b2a/tests/test.py#L104-L108) I can't for the life of me figure out where in the pipeline it is getting added, but it does not show up in the interface and is therefore does not have even cosmetic repercussions for the analyst. I left the test failing on that  assertion so that it is properly documented as adding the newline char.

**Comment by Rafiot** [comment]
Looks really cool, reviewing it now/over the weekend and merging asap

**Comment by Rafiot** [comment]
Done, and tests fixed: https://github.com/MISP/misp-modules/commit/3f83357a2d44e51c4c565443203edfabc12da238

**Comment by adulau** [comment]
Could you have a look at this https://github.com/MISP/misp-modules/issues/88 ? It seems indeed that the logic is missing for such case. Thanks a lot.

**Pull request merged**
