### PR TITLE
IPQualityScore MISP Expansion Module Integration

### PR DESCRIPTION
**Pull request by RamboV**
This pull request is for integrating IPQualityScore into MISP as an Expansion Module.

### CODE REVIEW

**Comment by adulau** [comment]
Thank you very much for the pull-request. Could you update `__init__.py` import to resolve the conflict and include the recent modules?

**Comment by RamboV** [comment]
> Thank you very much for the pull-request. Could you update `__init__.py` import to resolve the conflict and include the recent modules?

Hi @adulau , Thanks for the quick response, I have just updated it, please do let me know if anything else to be done.

**Comment by adulau** [comment]
Looks awesome! Thank you very much for the contribution!

**Comment by RamboV** [comment]
> Looks awesome! Thank you very much for the contribution!

Thank You very much... just wanted to ask when this module will be listed here?https://github.com/MISP/misp-modules#expansion-modules

**Pull request merged**
