### PR TITLE
Make it a package

### LINKED ISSUE #27: Easing deployment: implement as installable application
Will the project be open to implementing MISP modules as an installable Python package and publishing releases on PyPI? It would be fantastic to simply `pip install misp-modules` or similar, and for the script at *bin/misp-modules.py* to be migrated to a setuptools entry-point.

This would significantly ease deployment and aid use cases like installing into a virtualenv, etc.

### PR DESCRIPTION
**Pull request by Rafiot**
Works for me, can you give a try, please? 

fix #27

### CODE REVIEW

**Comment by Rafiot** [comment]
Do not merge, it doesn't work of you run it outside of the directory... ;)

**Comment by Rafiot** [comment]
This one should work now. I tried a bunch of options, it works for me. Can you give a try, please?

**Comment by adulau** [comment]
Sure. I'll test on the prod^H^H^Htesting server ;-)

**Comment by adulau** [comment]
Just one little thing, it seems that there are some typos in the README where some slashes are missing for the modules.

**Comment by Rafiot** [comment]
True, fixed :)

**Pull request merged**
